site_name: MathWallet NFT Wiki
site_description: In Math We Trust!
site_author: MathWallet

site_url: https://mathwallet.github.io/nft_docs
repo_url: https://github.com/mathwallet/nft_docs

dev_addr: 0.0.0.0:8000

copyright: Copyright &copy; 2018 MathWallet

nav:
  - Home: index.md
  - English:
    # - 'home': en/preface.md
  - 中文:
    - '前言': cn/preface.md

plugins:
  - search

theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'indigo'
  logo: 'images/logo.svg'

extra:
  manifest: 'manifest.webmanifest'
  social:
    # - icon: fontawesome/brands/github-alt
    #   link: 'https://github.com/mathwallet'
    # - icon: fontawesome/brands/twitter-alt
    #   link: 'https://twitter.com/mathwallet'
